// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Input type for create todo
type NewTodo struct {
	// Todo text
	Text string `json:"text"`
	// User name to assign it to
	UserID string `json:"userId"`
}

// Todo type
type Todo struct {
	// id of todo
	ID string `json:"id"`
	// todo text
	Text string `json:"text"`
	// done or pending
	Done bool `json:"done"`
	// User this todo belongs to
	User *User `json:"user"`
}

// User type
type User struct {
	// unique id for user
	ID string `json:"id"`
	// name of user
	Name string `json:"name"`
}
